// CS 491
// Project 2: Part 2
// 11/23/12
//
// This program accomplishes the following tasks:
// 1. Generate a list of the IP addresses/ports that appear to act as servers (e.g. web,mail,tcp).
// 2. For each server, list the total number of connections and the total number of bytes served.
// 3. Detect a probable port scan attack on a speci?ed target address. This is very open-ended, but at
//    a minimum you should be able to detect a simple SYN scan of a single host generated by nmap
//    using its default target port selection (a random ordering of the 1000 most common ports). But feel
//    free to get more elaborate.
//
// Example command-line compilation (MCECS Linux Lab):
// gcc -Wall -o port_scan port_scan.c -lpcap
//
// Example command-line run:
// port_scan < [PCAP trace file]
//
// ---------------------------------------------------------------
//
// This is a modified version of the sniffex demonstration program
// found in the following tutorial:
//
// http://www.tcpdump.org/pcap.html
//
// The original program was written by Tim Carstens and Guy Harris.
//

#include <pcap.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

/* default snap length (maximum bytes per packet to capture) */
#define SNAP_LEN 1518

/* ethernet headers are always exactly 14 bytes [1] */
#define SIZE_ETHERNET 14

/* Ethernet addresses are 6 bytes */
#define ETHER_ADDR_LEN	6

/* Ethernet header */
struct sniff_ethernet {
        u_char  ether_dhost[ETHER_ADDR_LEN];    /* destination host address */
        u_char  ether_shost[ETHER_ADDR_LEN];    /* source host address */
        u_short ether_type;                     /* IP? ARP? RARP? etc */
};

/* IP header */
struct sniff_ip {
        u_char  ip_vhl;                 /* version << 4 | header length >> 2 */
        u_char  ip_tos;                 /* type of service */
        u_short ip_len;                 /* total length */
        u_short ip_id;                  /* identification */
        u_short ip_off;                 /* fragment offset field */
        #define IP_RF 0x8000            /* reserved fragment flag */
        #define IP_DF 0x4000            /* dont fragment flag */
        #define IP_MF 0x2000            /* more fragments flag */
        #define IP_OFFMASK 0x1fff       /* mask for fragmenting bits */
        u_char  ip_ttl;                 /* time to live */
        u_char  ip_p;                   /* protocol */
        u_short ip_sum;                 /* checksum */
        struct  in_addr ip_src,ip_dst;  /* source and dest address */
};
#define IP_HL(ip)               (((ip)->ip_vhl) & 0x0f)
#define IP_V(ip)                (((ip)->ip_vhl) >> 4)

/* TCP header */
typedef u_int tcp_seq;

struct sniff_tcp {
        u_short th_sport;               /* source port */
        u_short th_dport;               /* destination port */
        tcp_seq th_seq;                 /* sequence number */
        tcp_seq th_ack;                 /* acknowledgement number */
        u_char  th_offx2;               /* data offset, rsvd */
#define TH_OFF(th)      (((th)->th_offx2 & 0xf0) >> 4)
        u_char  th_flags;
        #define TH_FIN  0x01
        #define TH_SYN  0x02
        #define TH_RST  0x04
        #define TH_PUSH 0x08
        #define TH_ACK  0x10
        #define TH_URG  0x20
        #define TH_ECE  0x40
        #define TH_CWR  0x80
        #define TH_FLAGS        (TH_FIN|TH_SYN|TH_RST|TH_ACK|TH_URG|TH_ECE|TH_CWR)
        u_short th_win;                 /* window */
        u_short th_sum;                 /* checksum */
        u_short th_urp;                 /* urgent pointer */
};

#define MAX_NUM_SERVERS 1024

typedef struct {
	int numServers;
	int servers[MAX_NUM_SERVERS];
} serverList;

// Adds unique entries to a list of TCP servers.
//
void build_server_list(u_char *args, const struct pcap_pkthdr *header, const u_char *packet)
{

	static int count = 1;                   /* packet counter */
	
	/* declare pointers to packet headers */
	const struct sniff_ip *ip;              /* The IP header */
	const struct sniff_tcp *tcp;            /* The TCP header */

	int size_ip;

	// Increment packet counter.
	//
	count++;
	
	/* define/compute ip header offset */
	ip = (struct sniff_ip*)(packet + SIZE_ETHERNET);
	size_ip = IP_HL(ip)*4;
	if (size_ip < 20) {
		printf("   * Invalid IP header length: %u bytes\n", size_ip);
		return;
	}

	// Check for TCP packet.
	//
	if (ip->ip_p != IPPROTO_TCP)
	{
		return;
	}
	
	/* define tcp header */
	tcp = (struct sniff_tcp*)(packet + SIZE_ETHERNET + size_ip);

	// Handle SYN/ACK packet.
	//
	if ((tcp->th_flags & TH_SYN) && (tcp->th_flags & TH_ACK))
	{	
		serverList *sl = (serverList*) args;
		int i;
		for (i = 0; i < sl->numServers; i++)
		{
			if (sl->servers[i] == ip->ip_src.s_addr)
			{
				return;
			}
		}
		if (i < MAX_NUM_SERVERS)
		{
			sl->numServers++;
			sl->servers[i] = ip->ip_src.s_addr;
		}
	}
	//
	// Handle ACK packet.
	//
	else if (!(tcp->th_flags & TH_SYN) && (tcp->th_flags & TH_ACK))
	{
	}
	//
	// Handle RST packet.
	//
	else if (tcp->th_flags & TH_RST)
	{
	}

return;
}

int main(int argc, char **argv)
{
	char errbuf[PCAP_ERRBUF_SIZE];		/* error buffer */
	pcap_t *handle;				/* packet capture handle */

	// Parse only TCP packets.
	//
	//char filter_exp[] = "tcp";		/* filter expression [3] */
	char filter_exp[] = "ip host != localhost";

	struct bpf_program fp;			/* compiled filter program (expression) */
	int num_packets = 50000;		/* number of packets to capture */

	// Used to store list of server IP addresses.
	//
	serverList sl;
	sl.numServers = 0;

	// Open PCAP trace file for reading.
	// (We read the file directly from stdin.)
	//
	handle = pcap_open_offline("-", errbuf);
	if (handle == NULL)
	{
		printf("pcap_open_offline(): %s\n", errbuf);
		exit(EXIT_FAILURE);
	}

	/* compile the filter expression */
	if (pcap_compile(handle, &fp, filter_exp, 0, PCAP_NETMASK_UNKNOWN) == -1) {
		fprintf(stderr, "Couldn't parse filter %s: %s\n",
		    filter_exp, pcap_geterr(handle));
		exit(EXIT_FAILURE);
	}

	/* apply the compiled filter */
	if (pcap_setfilter(handle, &fp) == -1) {
		fprintf(stderr, "Couldn't install filter %s: %s\n",
		    filter_exp, pcap_geterr(handle));
		exit(EXIT_FAILURE);
	}

	// Set loopback function (and pass server list as parameter).
	//
	pcap_loop(handle, num_packets, build_server_list, (u_char*)&sl);

	/* cleanup */
	pcap_freecode(&fp);
	pcap_close(handle);

	// Print server list.
	//
	int i;
	for (i = 0; i < sl.numServers; i++)
	{
		// Conversion to dotted decimal notation.
		//
		printf("%d", (sl.servers[i] & 0x000000ff));
		printf(".%d", ((sl.servers[i] >> 8) & 0x000000ff));
		printf(".%d", ((sl.servers[i] >> 16) & 0x000000ff));
		printf(".%d\n", ((sl.servers[i] >> 24) & 0x000000ff));
	}

return 0;
}